import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
// example v1.0.0 a407763253f0de6564e955215ce39428426e1ff9
//
// Code generated by webrpc-gen@v0.37.2 with .. generator. DO NOT EDIT.
//
// webrpc-gen -schema=../_examples/ClientExample/service.ridl -target=.. -client -out=../_examples/ClientExample/Sources/ClientExample/ExampleServiceClient.swift

public let WEBRPC_VERSION = "v1"
public let WEBRPC_SCHEMA_VERSION = "v1.0.0"
public let WEBRPC_SCHEMA_HASH = "a407763253f0de6564e955215ce39428426e1ff9"

public let WEBRPC_HEADER = "Webrpc"
public let WEBRPC_HEADER_VALUE = "webrpc@v0.37.2;..@unknown;example@v1.0.0"

public struct WebRPCGeneratedVersions: Sendable, Equatable {
    public let webrpcGenVersion: String
    public let codeGenName: String
    public let codeGenVersion: String
    public let schemaName: String
    public let schemaVersion: String

    public init(
        webrpcGenVersion: String = "",
        codeGenName: String = "",
        codeGenVersion: String = "",
        schemaName: String = "",
        schemaVersion: String = ""
    ) {
        self.webrpcGenVersion = webrpcGenVersion
        self.codeGenName = codeGenName
        self.codeGenVersion = codeGenVersion
        self.schemaName = schemaName
        self.schemaVersion = schemaVersion
    }

    public static let empty = WebRPCGeneratedVersions()
}

public func versionFromHeader(_ headers: [String: String]) -> WebRPCGeneratedVersions {
    guard let headerValue = webRPCHeaderValue(in: headers) else {
        return .empty
    }
    return parseWebRPCGeneratedVersions(headerValue)
}

public func versionFromHeader(_ response: WebRPCHTTPResponse) -> WebRPCGeneratedVersions {
    versionFromHeader(response.headers)
}

private func webRPCHeaderValue(in headers: [String: String]) -> String? {
    for (name, value) in headers {
        if name.caseInsensitiveCompare(WEBRPC_HEADER) == .orderedSame {
            return value
        }
    }
    return nil
}

private func parseWebRPCGeneratedVersions(_ header: String) -> WebRPCGeneratedVersions {
    let versions = header.split(separator: ";", omittingEmptySubsequences: false)
    guard versions.count >= 3 else {
        return .empty
    }

    let webrpcParts = versions[0].split(separator: "@", maxSplits: 1, omittingEmptySubsequences: false)
    let codeGenParts = versions[1].split(separator: "@", maxSplits: 1, omittingEmptySubsequences: false)
    let schemaParts = versions[2].split(separator: "@", maxSplits: 1, omittingEmptySubsequences: false)

    return WebRPCGeneratedVersions(
        webrpcGenVersion: webrpcParts.count > 1 ? String(webrpcParts[1]) : "",
        codeGenName: codeGenParts.count > 0 ? String(codeGenParts[0]) : "",
        codeGenVersion: codeGenParts.count > 1 ? String(codeGenParts[1]) : "",
        schemaName: schemaParts.count > 0 ? String(schemaParts[0]) : "",
        schemaVersion: schemaParts.count > 1 ? String(schemaParts[1]) : ""
    )
}

private func makeWebRPCHeaders(
    _ headers: [String: String],
    includeWebRPCHeader: Bool
) -> [String: String] {
    var requestHeaders = headers
    if includeWebRPCHeader {
        requestHeaders[WEBRPC_HEADER] = WEBRPC_HEADER_VALUE
    }
    return requestHeaders
}

public enum WebRPCJSON {
    public static func makeEncoder() -> JSONEncoder {
        JSONEncoder()
    }

    public static func makeDecoder() -> JSONDecoder {
        JSONDecoder()
    }
}

public struct WebRPCNull: Codable, Sendable {
    public init() {}

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        guard container.decodeNil() else {
            throw DecodingError.typeMismatch(
                WebRPCNull.self,
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "Expected null",
                ),
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encodeNil()
    }
}

public enum WebRPCJSONValue: Codable, Sendable {
    case object([String: WebRPCJSONValue])
    case array([WebRPCJSONValue])
    case string(String)
    case integer(Int64)
    case unsignedInteger(UInt64)
    case number(Double)
    case bool(Bool)
    case null

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()

        if container.decodeNil() {
            self = .null
        } else if let value = try? container.decode(Bool.self) {
            self = .bool(value)
        } else if let value = try? container.decode(Int64.self) {
            self = .integer(value)
        } else if let value = try? container.decode(UInt64.self) {
            self = .unsignedInteger(value)
        } else if let value = try? container.decode(Double.self) {
            self = .number(value)
        } else if let value = try? container.decode(String.self) {
            self = .string(value)
        } else if let value = try? container.decode([WebRPCJSONValue].self) {
            self = .array(value)
        } else if let value = try? container.decode([String: WebRPCJSONValue].self) {
            self = .object(value)
        } else {
            throw DecodingError.dataCorruptedError(
                in: container,
                debugDescription: "Unsupported JSON value",
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()

        switch self {
        case .object(let value):
            try container.encode(value)
        case .array(let value):
            try container.encode(value)
        case .string(let value):
            try container.encode(value)
        case .integer(let value):
            try container.encode(value)
        case .unsignedInteger(let value):
            try container.encode(value)
        case .number(let value):
            try container.encode(value)
        case .bool(let value):
            try container.encode(value)
        case .null:
            try container.encodeNil()
        }
    }
}

public protocol WebRPCEnumKey: Hashable, Sendable {
    init(wireValue: String)
    var wireValue: String { get }
}

public struct WebRPCEnumMap<Key, Value>: Codable, Sendable
where Key: WebRPCEnumKey, Value: Codable & Sendable {
    public var values: [Key: Value]

    public init(_ values: [Key: Value] = [:]) {
        self.values = values
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let rawValues = try container.decode([String: Value].self)

        var values: [Key: Value] = [:]
        values.reserveCapacity(rawValues.count)

        for (key, value) in rawValues {
            values[Key(wireValue: key)] = value
        }

        self.values = values
    }

    public func encode(to encoder: Encoder) throws {
        let rawValues = Dictionary(uniqueKeysWithValues: values.map { ($0.key.wireValue, $0.value) })
        var container = encoder.singleValueContainer()
        try container.encode(rawValues)
    }
}

public struct WebRPCHTTPResponse: Sendable {
    public let statusCode: Int
    public let body: Data
    public let headers: [String: String]

    public init(
        statusCode: Int,
        body: Data,
        headers: [String: String] = [:]
    ) {
        self.statusCode = statusCode
        self.body = body
        self.headers = headers
    }
}

public protocol WebRPCTransport: Sendable {
    func post(
        baseURL: String,
        path: String,
        body: Data,
        headers: [String: String]
    ) async throws -> WebRPCHTTPResponse
}

public struct WebRPCTransportError: Error, Sendable {
    public let message: String
    public let underlyingDescription: String?

    public init(message: String, underlyingDescription: String? = nil) {
        self.message = message
        self.underlyingDescription = underlyingDescription
    }
}

public struct URLSessionWebRPCTransport: WebRPCTransport, @unchecked Sendable {
    public let session: URLSession

    public init(session: URLSession = .shared) {
        self.session = session
    }

    public func post(
        baseURL: String,
        path: String,
        body: Data,
        headers: [String: String]
    ) async throws -> WebRPCHTTPResponse {
        guard let url = URL(string: joinWebRPCURL(baseURL: baseURL, path: path)) else {
            throw WebRPCTransportError(message: "Invalid WebRPC URL")
        }

        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.httpBody = body
        request.setValue("application/json; charset=utf-8", forHTTPHeaderField: "Content-Type")

        for (name, value) in headers {
            request.setValue(value, forHTTPHeaderField: name)
        }

        do {
            let (data, response) = try await session.data(for: request)
            let httpResponse = response as? HTTPURLResponse
            let responseHeaders = (httpResponse?.allHeaderFields ?? [:]).reduce(into: [String: String]()) { result, item in
                guard let key = item.key as? String else {
                    return
                }
                result[key] = String(describing: item.value)
            }

            return WebRPCHTTPResponse(
                statusCode: httpResponse?.statusCode ?? 0,
                body: data,
                headers: responseHeaders,
            )
        } catch is CancellationError {
            throw CancellationError()
        } catch {
            throw WebRPCTransportError(
                message: "WebRPC HTTP request failed",
                underlyingDescription: String(describing: error),
            )
        }
    }
}

private func joinWebRPCURL(baseURL: String, path: String) -> String {
    baseURL.trimmingCharacters(in: CharacterSet(charactersIn: "/")) + "/" + path.trimmingCharacters(in: CharacterSet(charactersIn: "/"))
}

public func executeWebRPC<Response>(
    baseURL: String,
    urlPath: String,
    body: Data,
    transport: any WebRPCTransport,
    headers: [String: String] = [:],
    decodeSuccess: (Data, JSONDecoder) throws -> Response
) async throws -> Response {
    let response: WebRPCHTTPResponse
    do {
        response = try await transport.post(
            baseURL: baseURL,
            path: urlPath,
            body: body,
            headers: headers,
        )
    } catch is CancellationError {
        throw CancellationError()
    } catch let error as WebRPCTransportError {
        throw error
    } catch {
        throw WebRPCTransportError(
            message: "WebRPC request failed",
            underlyingDescription: String(describing: error),
        )
    }

    guard (200...299).contains(response.statusCode) else {
        throw decodeWebRPCError(statusCode: response.statusCode, data: response.body)
    }

    do {
        return try decodeSuccess(response.body, WebRPCJSON.makeDecoder())
    } catch let error as WebRPCError {
        throw error
    } catch {
        throw webRPCBadResponseError(
            statusCode: response.statusCode,
            data: response.body,
            cause: String(describing: error)
        )
    }
}

public enum WebRPCErrorKind: Sendable {
    case webrpcEndpoint
    case webrpcRequestFailed
    case webrpcBadRoute
    case webrpcBadMethod
    case webrpcBadRequest
    case webrpcBadResponse
    case webrpcServerPanic
    case webrpcInternalError
    case webrpcClientAborted
    case webrpcStreamLost
    case webrpcStreamFinished
    case unknown

    public var code: Int {
        switch self {
        case .webrpcEndpoint:
            return 0
        case .webrpcRequestFailed:
            return -1
        case .webrpcBadRoute:
            return -2
        case .webrpcBadMethod:
            return -3
        case .webrpcBadRequest:
            return -4
        case .webrpcBadResponse:
            return -5
        case .webrpcServerPanic:
            return -6
        case .webrpcInternalError:
            return -7
        case .webrpcClientAborted:
            return -8
        case .webrpcStreamLost:
            return -9
        case .webrpcStreamFinished:
            return -10
        case .unknown:
            return -999
        }
    }

    public static func fromCode(_ code: Int) -> WebRPCErrorKind {
        switch code {
        case 0:
            return .webrpcEndpoint
        case -1:
            return .webrpcRequestFailed
        case -2:
            return .webrpcBadRoute
        case -3:
            return .webrpcBadMethod
        case -4:
            return .webrpcBadRequest
        case -5:
            return .webrpcBadResponse
        case -6:
            return .webrpcServerPanic
        case -7:
            return .webrpcInternalError
        case -8:
            return .webrpcClientAborted
        case -9:
            return .webrpcStreamLost
        case -10:
            return .webrpcStreamFinished
        default:
            return .unknown
        }
    }
}

public struct WebRPCError: Error, Sendable {
    public let error: String
    public let code: Int
    public let message: String
    public let cause: String
    public let status: Int
    public let kind: WebRPCErrorKind

    public init(
        error: String,
        code: Int,
        message: String,
        cause: String,
        status: Int,
        kind: WebRPCErrorKind
    ) {
        self.error = error
        self.code = code
        self.message = message
        self.cause = cause
        self.status = status
        self.kind = kind
    }
}

private struct WebRPCErrorPayload: Decodable, Sendable {
    let error: String?
    let code: Int?
    let msg: String?
    let cause: String?
    let status: Int?
}

public func decodeWebRPCError(
    statusCode: Int,
    data: Data,
    decoder: JSONDecoder = WebRPCJSON.makeDecoder()
) -> WebRPCError {
    do {
        let payload = try decoder.decode(WebRPCErrorPayload.self, from: data)
        let code = payload.code ?? WebRPCErrorKind.unknown.code
        return WebRPCError(
            error: payload.error ?? "WebrpcEndpoint",
            code: code,
            message: payload.msg ?? "endpoint error",
            cause: payload.cause ?? "",
            status: payload.status ?? statusCode,
            kind: WebRPCErrorKind.fromCode(code),
        )
    } catch {
        return webRPCBadResponseError(
            statusCode: statusCode,
            data: data,
            cause: "Unable to decode error response"
        )
    }
}

private func webRPCBadResponseError(
    statusCode: Int,
    data: Data,
    cause: String
) -> WebRPCError {
    let bodyText = String(data: data, encoding: .utf8) ?? "<non-utf8 body>"
    return WebRPCError(
        error: "WebrpcBadResponse",
        code: WebRPCErrorKind.webrpcBadResponse.code,
        message: "bad response",
        cause: "\(cause): \(bodyText)",
        status: statusCode,
        kind: .webrpcBadResponse
    )
}



// MARK: - Types
public enum TransactionStatus: Codable, Hashable, Sendable, WebRPCEnumKey {
    case unknown
    case pending
    case succeeded
    case unknownValue(String)

    public var wireValue: String {
        switch self {
        case .unknown:
            return "UNKNOWN"
        case .pending:
            return "PENDING"
        case .succeeded:
            return "SUCCEEDED"
        case .unknownValue(let value):
            return value
        }
    }

    public init(wireValue: String) {
        switch wireValue {
        case "UNKNOWN":
            self = .unknown
        case "PENDING":
            self = .pending
        case "SUCCEEDED":
            self = .succeeded
        default:
            self = .unknownValue(wireValue)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let value = try container.decode(String.self)
        self = TransactionStatus(wireValue: value)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(wireValue)
    }
}



public struct RuntimeStatus: Codable, Sendable {
    public let healthy: Bool
    public let version: String

    public init(healthy: Bool, version: String
    ) {
        self.healthy = healthy
        self.version = version
    }
    enum CodingKeys: String, CodingKey {
        case healthy = "healthy"
        case version = "version"
    }
}



public struct TransactionEnvelope: Codable, Sendable {
    public let id: String
    public let status: TransactionStatus

    public init(id: String, status: TransactionStatus
    ) {
        self.id = id
        self.status = status
    }
    enum CodingKeys: String, CodingKey {
        case id = "id"
        case status = "status"
    }
}



public struct InternalOnly: Codable, Sendable {

    public init(
    ) {
    }
    enum CodingKeys: CodingKey {
    }
}






public enum ExampleServiceAPI {
    public static let basePath = "/rpc/ExampleService"

    public enum Ping {
        public static let path = "/Ping"
        public static let urlPath = "/rpc/ExampleService/Ping"

        public struct Response: Codable, Sendable {
            public let version: String

            public init(version: String
            ) {
                self.version = version
            }
            enum CodingKeys: String, CodingKey {
                case version = "version"
            }
        }
        public static func encodeRequest(encoder _: JSONEncoder = WebRPCJSON.makeEncoder()) throws -> Data {
            Data("{}".utf8)
        }

        public static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> ExampleServiceAPI.Ping.Response {
            try decoder.decode(ExampleServiceAPI.Ping.Response.self, from: data)
        }
    }

    public enum RuntimeStatusMethod {
        public static let path = "/RuntimeStatus"
        public static let urlPath = "/rpc/ExampleService/RuntimeStatus"

        public struct Response: Codable, Sendable {
            public let status: RuntimeStatus

            public init(status: RuntimeStatus
            ) {
                self.status = status
            }
            enum CodingKeys: String, CodingKey {
                case status = "status"
            }
        }
        public static func encodeRequest(encoder _: JSONEncoder = WebRPCJSON.makeEncoder()) throws -> Data {
            Data("{}".utf8)
        }

        public static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> ExampleServiceAPI.RuntimeStatusMethod.Response {
            try decoder.decode(ExampleServiceAPI.RuntimeStatusMethod.Response.self, from: data)
        }
    }

    public enum EchoTransaction {
        public static let path = "/EchoTransaction"
        public static let urlPath = "/rpc/ExampleService/EchoTransaction"
        public static func encodeRequest(
            _ request: TransactionEnvelope,
            encoder: JSONEncoder = WebRPCJSON.makeEncoder()
        ) throws -> Data {
            try encoder.encode(request)
        }

        public static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> TransactionEnvelope {
            try decoder.decode(TransactionEnvelope.self, from: data)
        }
    }

    public enum EchoInternal {
        public static let path = "/EchoInternal"
        public static let urlPath = "/rpc/ExampleService/EchoInternal"
        public static func encodeRequest(
            _ request: InternalOnly,
            encoder: JSONEncoder = WebRPCJSON.makeEncoder()
        ) throws -> Data {
            try encoder.encode(request)
        }

        public static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> InternalOnly {
            try decoder.decode(InternalOnly.self, from: data)
        }
    }
}

public struct ExampleServiceClient: Sendable {
    public let baseURL: String
    public let transport: any WebRPCTransport
    public let headers: @Sendable () -> [String: String]

    public init(
        baseURL: String,
        transport: any WebRPCTransport = URLSessionWebRPCTransport(),
        headers: @escaping @Sendable () -> [String: String] = { [:] }
    ) {
        self.baseURL = baseURL
        self.transport = transport
        self.headers = headers
    }

    public func ping() async throws -> ExampleServiceAPI.Ping.Response {
        let body = try ExampleServiceAPI.Ping.encodeRequest()
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: ExampleServiceAPI.Ping.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: ExampleServiceAPI.Ping.decodeResponse,
        )
    }

    public func runtimeStatus() async throws -> ExampleServiceAPI.RuntimeStatusMethod.Response {
        let body = try ExampleServiceAPI.RuntimeStatusMethod.encodeRequest()
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: ExampleServiceAPI.RuntimeStatusMethod.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: ExampleServiceAPI.RuntimeStatusMethod.decodeResponse,
        )
    }

    public func echoTransaction(_ request:TransactionEnvelope) async throws -> TransactionEnvelope {
        let body = try ExampleServiceAPI.EchoTransaction.encodeRequest(request)
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: ExampleServiceAPI.EchoTransaction.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: ExampleServiceAPI.EchoTransaction.decodeResponse,
        )
    }

    public func echoInternal(_ request:InternalOnly) async throws -> InternalOnly {
        let body = try ExampleServiceAPI.EchoInternal.encodeRequest(request)
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: ExampleServiceAPI.EchoInternal.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: ExampleServiceAPI.EchoInternal.decodeResponse,
        )
    }
}


